### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by stygiansabyss** [ooyala/php-v2-sdk#5]
I see the composer.json file, but this package is not available on composer.  Is this something that is coming?

**Comment by morganestes** [comment]
I've also tried adding this using Composer's repository syntax and it's not working.

+1 to adding to Packagist so it can be included easily. https://packagist.org/packages/submit

**Comment by Madrigal** [comment]
Package is up https://packagist.org/packages/ooyala/v2-api

Please let us know if you bump into any issues

**Comment by stygiansabyss** [comment]
Thank you for this sir :)
